application:
  open-api:
    title: Sign-In API
    version: 1.0
    description: API documentation of customer verification
  otp:
    length: 4
    ttl: 180s
  email:
    api-key: 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
    subject: Verification code
    from:
      email: vvvorotnik@ukr.net
      name:  Volodymyr Vorotnikov

springdoc:
  default-produces-media-type: application/json
  writer-with-default-pretty-printer: true
  swagger-ui:
    path: /
  api-docs:
    path: /v3/api-docs

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include:
          - health
          - info

  server:
    port: 8081
    base-path: /^project.name^

spring:
  main:
    banner-mode: off
  datasource:
#    url: jdbc:postgresql://host.docker.internal:5433/postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password


  application:
    name: ^project.name^

  flyway:
    enabled: true
    baseline-on-migrate: true
    clean-on-validation-error: true

  jpa:
    open-in-view: false
    properties:
      hibernate:
        enabled: true
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 20
          fetch_size: 20
          batch_versioned_data: true
    hibernate:
      ddl-auto: validate

  mvc:
    throw-exception-if-no-handler-found: true

  messages:
    basename: messages
    fallback-to-system-locale: false

  jackson:
    serialization:
      write-dates-as-timestamps: true
      write-date-timestamps-as-nanoseconds: false

  web:
    resources:
      add-mappings: false

server:
  forward-headers-strategy: framework
  shutdown: graceful
  port: 8088

logging:
  level:
    com.backend: debug
    org.springframework:
      web: debug
      orm: debug